---product_details----
create table product_details
(
plant_id number generated by default as identity(start with 1001 increment by 1), 
plant_name varchar(30)not null,
plant_description varchar(1000),
plant_price number(10),
category_name varchar2(20),
constraint pk_plaid primary key(plant_id)
);
select *from product_details;

delete from product_details;
desc product_details;
drop table product_details;
commit;


insert into product_details (plant_name,plant_description,plant_price,category_name) values('curryplant','The leaves of this plant are used in most of the Indian curries and adds a special aroma to the dishes',200,'medicinal');
insert into product_details (plant_name,plant_description,plant_price,category_name) values('two layer bamboo','Two-layered lucky bamboo is an expression of love and is also said to double your luck',250,'bamboo');
insert into product_details (plant_name,plant_description,plant_price,category_name) values('red hibiscus plant','Hibiscus is a genus of flowering plants in the mallow family',100,'flowering plant');
insert into product_details (plant_name,plant_description,plant_price,category_name) values('thulsi plant',' helps in the healing of the human body',400,'medicinal');
insert into product_details (plant_name,plant_description,plant_price,category_name) values('green money plant','money plant is good for wealth',150,'money plant');
----user_details------
select * from user_details;
create table user_details(user_id number generated by default as identity(start with 1 increment by 1),
user_name varchar2(30),
email_id varchar2(30),
user_password varchar2(20),mobile_number number(10),
address varchar2(100),role_name varchar2(10) default 'user',
constraint pk_user_id primary key(user_id)
);
alter table user_details drop column role_name ;
alter table user_details add role_name varchar2(10) default 'user'; 
desc user_details;
select *from user_details;
insert into user_details(user_name,email_id,user_password,mobile_number,address,role_name)values('sangeetha','sangi412@gmail.com','sangi6123',8940157879,'madurai','admin');

alter table user_details modify role varchar2(10) default 'user';
drop  table user_details;
select * from user_details where user_role='admin' and Email_id='sangi412@gmail.com' and user_password='sangi6123';
delete from user_detail where user_id=21;
select * from user_details;
-----orders-----
create table plant_orders(
order_id number generated by default as identity(start with 2001 increment by 1),
user_id number,
plant_id number,
quantity int,
total_price number(10,2),
constraint pk_ordid primary key(order_id),
constraint fk_useid foreign key(user_id) references user_details(user_id),
costraint fk_planid foreign key(plant_id) references product_details(plant_id)
);
select * from plant_orders;
drop table orders;
select * from order_items;
alter table order_items add delevery_date date;
---order_items---
select * from order_details;
create  table payment(
item_id number generated by default as identity(start with 3001 increment by 1),
order_id number,
order_status varchar2(50),
order_date date,
constraint fk_orderid foreign key(order_id) references plant_orders(order_id)



update product_details set plant_name ='neemplant'  where plant_id=1002;
select * from user_details;
select * from product_details;
desc product_details;
desc product_details;
commit;
select * from plant_orders;
select * from product_details where plant_id=1003;

-----order_details---
create table order_details(orders_id number generated by default as identity(start with 4001 increment by 1)primary key,
user_id number,plant_id number,quantity int ,totalprice number(10),address varchar2(200),order_date date default sysdate,constraint fk_userid foreign key(user_id)
references user_details(user_id),constraint fk_plantid foreign key(plant_id)
references product_details(plant_id));
--drop table order_details;
select * from user_details;
commit;
update user_details set wallet=0 where role_name='admin';
alter table user_details add wallet number default 50000; 
select * from order_details;